services:

    # ---Load balancer---
    apache:
        build: apache/
        ports:
            - 8002:80


    # ---XWiki Nodes---
    tomcat:
        build: tomcat/
        # ports:
        #     - 8002:8080
        deploy:
            resources:
                limits:
                    memory: 16G
            mode: replicated
            replicas: 2
        volumes:
            # Note: This volume also contains the hsqldb(default) database.
            - ./data/tomcat:/usr/local/tomcat/webapps/xwiki

        env_file:
            - env/connector/${DB_TYPE}.env
            - env/tomcat.env
            - .env
    # ---Solr---
    solr:
        build: solr/
        volumes:
            - ./data/solr:/var/solr
        ports:
            - 8983:8983
        profiles:
            - solr-remote
        # command:
        #     - solr-precreate
        #     - gettingstarted

    # ---Databases---
    mariadb:
        image: mariadb
        env_file:
            - env/db/mariadb.env
            - .env
        volumes:
            - ./data/mariadb:/var/lib/mysql
        profiles:
            - mariadb

    postgresql:
        image: postgres
        env_file:
            - env/db/postgresql.env
            - .env
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        profiles:
            - postgresql

    mysql:
        image: mysql
        env_file:
            - env/db/mysql.env
            - .env
        volumes:
            - ./data/mysql:/var/lib/mysql
        profiles:
            - mysql
