version: '3'

x-tomcat:
    &tomcat
    build: tomcat/
    networks:
        - web
        - cluster
        - database
        - solr
    env_file:
        - env/connector/${DB_TYPE}.env
        - env/tomcat.env
        - .env
    depends_on:
        - gossip

# ---Global definitions---
volumes:
    tomcat-attachments:
    node1:
    node2:
    solr:
    mariadb:
    postgresql:
    mysql:

networks:
    web:
    cluster:
        internal: true
    database:
        internal: true
    solr:
        internal: true

services:

    # ---Load balancer---
    apache:
        build: apache/
        ports:
            - 8080:80
        networks:
            - web
        environment:
            NODES: node1 node2

    # ---Gossip Router---
    gossip:
        image: jboss/jgroups-gossip
        networks:
            - cluster

    # ---XWiki Nodes---
    node1:
        <<: *tomcat
        volumes:
            - node1:$TOMCAT_XWIKI_PATH
            - tomcat-attachments:/usr/local/tomcat/webapps/xwiki/data/store/file
        environment:
            NODE_NAME: "node1"
    node2:
        <<: *tomcat
        volumes:
            - node2:$TOMCAT_XWIKI_PATH
            - tomcat-attachments:/usr/local/tomcat/webapps/xwiki/data/store/file
        environment:
            NODE_NAME: "node2"

    # ---Solr---
    solr:
        build: solr/
        volumes:
            - solr:/var/solr
        networks:
            - solr
        profiles:
            - solr-remote

    # ---Databases---
    mariadb:
        image: mariadb
        env_file:
            - env/db/mariadb.env
            - .env
        volumes:
            - mariadb:/var/lib/mysql
        networks:
            - database
        profiles:
            - mariadb

    postgresql:
        image: postgres
        env_file:
            - env/db/postgresql.env
            - .env
        volumes:
            - postgresql:/var/lib/postgresql/data
        networks:
            - database
        profiles:
            - postgresql

    mysql:
        image: mysql
        env_file:
            - env/db/mysql.env
            - .env
        volumes:
            - mysql:/var/lib/mysql
        networks:
            - database
        profiles:
            - mysql
