services:

    # ---Load balancer---
    apache:
        build: apache/
        ports:
            - 8002:80
        networks:
            - cluster


    # ---XWiki Nodes---
    tomcat:
        build: tomcat/
        volumes:
            # Note: This volume also contains the hsqldb(default) database.
            - ./data/tomcat:/usr/local/tomcat/webapps/xwiki
        networks:
            - cluster
            - database
            - solr
        deploy:
            resources:
                limits:
                    memory: 16G
            mode: replicated
            replicas: 1

        env_file:
            - env/connector/${DB_TYPE}.env
            - env/tomcat.env
            - .env


    # ---Solr---
    solr:
        build: solr/
        volumes:
            - ./data/solr:/var/solr
        networks:
            - solr
        profiles:
            - solr-remote

    # ---Databases---
    mariadb:
        image: mariadb
        env_file:
            - env/db/mariadb.env
            - .env
        volumes:
            - ./data/mariadb:/var/lib/mysql
        networks:
            - database
        profiles:
            - mariadb

    postgresql:
        image: postgres
        env_file:
            - env/db/postgresql.env
            - .env
        volumes:
            - ./data/postgresql:/var/lib/postgresql/data
        networks:
            - database
        profiles:
            - postgresql

    mysql:
        image: mysql
        env_file:
            - env/db/mysql.env
            - .env
        volumes:
            - ./data/mysql:/var/lib/mysql
        networks:
            - database
        profiles:
            - mysql

networks:
    cluster:
    database:
    solr:
